"""Add Complaint model

Revision ID: 7f7ab19cc8ce
Revises: d30dd6bca94f
Create Date: 2025-04-24 11:37:48.839459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7ab19cc8ce'
down_revision = 'd30dd6bca94f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_complaint_user_id',
            'user',
            ['user_id'],
            ['id']
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('issue',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('room',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('date_created')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
